import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/header";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Blog app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider
          appearance={{
            theme: dark,
          }}
          allowedRedirectOrigins={["*", "http://localhost:3000", "http://*.localhost:3000"]}
        >
          <Header />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
